### ISSUE TITLE
After OJ is enabled for AMS, the speed test randomly failed

### ISSUE THREAD

**Issue by berniechiu** [Netflix/fast_jsonapi#51]
According to this PR https://github.com/Netflix/fast_jsonapi/pull/36, OJ is enabled for AMS

Now causing the benchmark spec randomly failed, looks like the speed factor is not quite consistent since it's random. I might look into this later anyway.

```ruby
  1) FastJsonapi::ObjectSerializer when comparing with AMS 0.10.x should serialize 1 records atleast 25 times faster than AMS
     Failure/Error: expect { our_serializer.serialized_json }.to perform_faster_than { ams_serializer.to_json }.at_least(speed_factor).times
       expected given block to perform faster than comparison block by at_least 25 times, but performed faster by 22.81 times
     # ./spec/lib/object_serializer_performance_spec.rb:77:in `block (4 levels) in <top (required)>'

  2) FastJsonapi::ObjectSerializer when comparing with AMS 0.10.x and with includes and meta should serialize 25 records atleast 25 times faster than AMS
     Failure/Error: expect { our_serializer.serialized_json }.to perform_faster_than { ams_serializer.to_json }.at_least(speed_factor).times
       expected given block to perform faster than comparison block by at_least 25 times, but performed faster by 19.94 times
     # ./spec/lib/object_serializer_performance_spec.rb:102:in `block (4 levels) in <top (required)>'

  3) FastJsonapi::ObjectSerializer when comparing with AMS 0.10.x and with includes and meta should serialize 250 records atleast 25 times faster than AMS
     Failure/Error: expect { our_serializer.serialized_json }.to perform_faster_than { ams_serializer.to_json }.at_least(speed_factor).times
       expected given block to perform faster than comparison block by at_least 25 times, but performed faster by 19.44 times
     # ./spec/lib/object_serializer_performance_spec.rb:102:in `block (4 levels) in <top (required)>'

Finished in 25.31 seconds (files took 0.74305 seconds to load)
49 examples, 3 failures

rspec './spec/lib/object_serializer_performance_spec.rb[1:2:1]' # FastJsonapi::ObjectSerializer when comparing with AMS 0.10.x should serialize 1 records atleast 25 times faster than AMS
rspec './spec/lib/object_serializer_performance_spec.rb[1:3:2]' # FastJsonapi::ObjectSerializer when comparing with AMS 0.10.x and with includes and meta should serialize 25 records atleast 25 times faster than AMS
rspec './spec/lib/object_serializer_performance_spec.rb[1:3:3]' # FastJsonapi::ObjectSerializer when comparing with AMS 0.10.x and with includes and meta should serialize 250 records atleast 25 times faster than AMS
```

**Comment by shishirmk** [comment]
We may need to clean up and remove the json string serialization performance tests altogether or make them information only. The gem controls only the ruby hash creation time after that its just multi json and the chosen engine.

**Comment by vovimayhem** [comment]
I understand - even praise - the performance criteria set up for this project. But maybe the "at least 25x" criteria is either a bit too much, or too inflexible for some scenarios that it's actually hitting this limit.

I'm seeing (right now) master fail a couple of performance tests by 1x or less... leaving no headroom for adding new features :( - I'm taking a jab at #37 right now, and given master fails by 1x, my branch failing at around 2x on those same tests I feel it's a bummer.

**Comment by shishirmk** [comment]
@vovimayhem We can change the 25x criteria. if the feature really needs some performance degradation we will lower the criteria. I think we should always start by discussing if we can implement the feature without any material change to performance. 

Here is an example of a sample discussion i enjoyed https://github.com/Netflix/fast_jsonapi/pull/49

**Comment by christophersansone** [comment]
Agreed with @shishirmk .  I love that the performance metrics are part of the process.  PRs that do not impact performance can be approved quickly, but implementations that have a performance impact will at least raise a red flag to the maintainers.  It may just require a minor tweak to fix the performance change, or we may be able to more tightly isolate the performance degradation to certain cases (e.g. a 10% degradation for polymorphic associations vs. a 10% degradation for all serialization).

**Comment by vovimayhem** [comment]
Agreed - see #64 :)

**Comment by shishirmk** [comment]
This is still an issue after the release of version `1.1.0` so i think we need to tackle this and ensure that performance tests are stable and stop failing erratically
